### PR TITLE
add SplashScreen

### PR DESCRIPTION
**Pull request by thierryH91200**
add SplashScreen

### CODE REVIEW

**Comment by lukakerr** [comment]
@thierryH91200 Thanks for this, it looks great! I've made a few changes but can't add them to this pull request until you give me access. Could you check the box "Allow edits from maintainers", so I can add a commit? More info here: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by lukakerr** [comment]
@thierryH91200 Thanks for this, it looks great! I had to merge it locally in 9891f32 since I made a few changes. All your work is now in master, so i'll close this.

**Comment by thierryH91200** [comment]
in class DocumentController: NSDocumentController {

```
// Ensure after opening a document that the splash screen window is closed
    for window in NSApp.windows {
      if let splashScreenWindow = window.windowController as? SplashScreenWindowController {
        splashScreenWindow.close()
      }
    }

```
I'm not sure it's a good idea when terminateAfterLastWindowClosed = true
Document is not open yet

**Comment by thierryH91200** [comment]
I have check the box "Allow edits from maintainers",  it's not memorized

**Pull request closed without merging**
